"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { useTranslations } from "next-intl";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { createExpense } from "@/actions/expense";

type Allocation = {
  id: string;
  nameLocal: string;
  remainingAmount: number;
  budget: {
    id: string;
    categoryId: string;
    divisionId: string;
    division: {
      nameLocal: string;
    };
  };
};

const formSchema = z.object({
  allocationId: z.string().min(1, "Project is required"),
  title: z.string().min(1, "Title is required"),
  amount: z.string().refine((val) => !isNaN(Number(val)) && Number(val) > 0, {
    message: "Amount must be a positive number",
  }),
  expenseDate: z.string().min(1, "Date is required"),
  description: z.string().min(1, "Description is required"),
});

export default function DisbursementModal({
  allocations,
}: {
  allocations: Allocation[];
}) {
  const [open, setOpen] = useState(false);
  const t = useTranslations();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      allocationId: "",
      title: "",
      amount: "",
      expenseDate: new Date().toISOString().split("T")[0],
      description: "",
    },
  });

  const selectedAllocationId = form.watch("allocationId");
  const selectedAllocation = allocations.find(
    (a) => a.id === selectedAllocationId
  );

  async function onSubmit(values: z.infer<typeof formSchema>) {
    if (!selectedAllocation) return;

    setIsSubmitting(true);
    try {
      // Generate a temporary code (in real app, this might be auto-generated by backend or user input)
      const code = `EXP-${Date.now().toString().slice(-6)}`;

      const result = await createExpense({
        code,
        budgetId: selectedAllocation.budget.id,
        budgetAllocationId: selectedAllocation.id,
        categoryId: selectedAllocation.budget.categoryId,
        divisionId: selectedAllocation.budget.divisionId,
        title: values.title,
        titleLocal: values.title, // Using same title for local for now
        description: values.description,
        descriptionLocal: values.description,
        amount: Number(values.amount),
        expenseDate: new Date(values.expenseDate),
      });

      if (result.success) {
        toast.success("Disbursement created successfully");
        setOpen(false);
        form.reset();
      } else {
        toast.error(result.error || "Failed to create disbursement");
      }
    } catch (error) {
      toast.error("An unexpected error occurred");
      console.error(error);
    } finally {
      setIsSubmitting(false);
    }
  }

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("th-TH", {
      style: "currency",
      currency: "THB",
      minimumFractionDigits: 2,
    }).format(amount);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button size="lg" variant="outline" className="min-w-[180px]">
          {t("budget.allocation.disburse")}
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>{t("budget.allocation.disburse")}</DialogTitle>
          <DialogDescription>
            Create a new expense record for a project.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="allocationId"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t("budget.allocation.projectName")}</FormLabel>
                  <Select
                    onValueChange={field.onChange}
                    defaultValue={field.value}
                  >
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select project" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {allocations.map((allocation) => (
                        <SelectItem key={allocation.id} value={allocation.id}>
                          {allocation.nameLocal}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            {selectedAllocation && (
              <div className="text-sm p-3 bg-muted rounded-md space-y-1">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Budget Balance:</span>
                  <span
                    className={
                      selectedAllocation.remainingAmount < 0
                        ? "text-red-500 font-bold"
                        : "font-bold"
                    }
                  >
                    {formatCurrency(selectedAllocation.remainingAmount)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Division:</span>
                  <span>{selectedAllocation.budget.division.nameLocal}</span>
                </div>
              </div>
            )}

            <FormField
              control={form.control}
              name="title"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Expense Title</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g. Equipment purchase" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="amount"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Amount (THB)</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        step="0.01"
                        placeholder="0.00"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="expenseDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Date</FormLabel>
                    <FormControl>
                      <Input type="date" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Details about this expense..."
                      className="resize-none"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <DialogFooter>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                Submit Disbursement
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
